/*******************************************************************************
 * Copyright (c) 2013-2016 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Initial Contributors:
 *     Thierry Monteil : Project manager, technical co-manager
 *     Mahdi Ben Alaya : Technical co-manager
 *     Samir Medjiah : Technical co-manager
 *     Khalil Drira : Strategy expert
 *     Guillaume Garzone : Developer
 *     François Aïssaoui : Developer
 *
 * New contributors :
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 03:56:27 PM CEST 
//

package org.eclipse.om2m.commons.resource;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.om2m.commons.constants.ShortName;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}mgmtResource">
 *       &lt;sequence>
 *         &lt;element name="devID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="devType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="areaNwkId" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="sleepInterval" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="sleepDuration" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listOfNeighbors" type="{http://www.onem2m.org/xml/protocols}listOfURIs"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = ShortName.ANDI)
public class AreaNwkDeviceInfo extends MgmtResource {

	@XmlElement(required = true, name = ShortName.DEV_ID)
	protected String devID;
	@XmlElement(required = true, name = ShortName.DEV_TYPE)
	protected String devType;
	@XmlElement(required = true, name = ShortName.AREA_NWK_ID)
	@XmlSchemaType(name = "anyURI")
	protected String areaNwkId;
	@XmlSchemaType(name = "nonNegativeInteger")
	@XmlElement(name = ShortName.SLEEP_INTERVAL)
	protected BigInteger sleepInterval;
	@XmlSchemaType(name = "nonNegativeInteger")
	@XmlElement(name = ShortName.SLEEP_DURATION)
	protected BigInteger sleepDuration;
	@XmlElement(name = ShortName.STATUS)
	protected String status;
	@XmlList
	@XmlElement(required = true, name = ShortName.LIST_OF_NEIGHBORS)
	protected List<String> listOfNeighbors;
	@XmlElement(name = ShortName.CHILD_RESOURCE)
	protected List<ChildResourceRef> childResource;
	@XmlElement(namespace = "http://www.onem2m.org/xml/protocols", name = ShortName.SUB)
	protected List<Subscription> subscription;

	/**
	 * Gets the value of the devID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDevID() {
		return devID;
	}

	/**
	 * Sets the value of the devID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDevID(String value) {
		this.devID = value;
	}

	/**
	 * Gets the value of the devType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDevType() {
		return devType;
	}

	/**
	 * Sets the value of the devType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDevType(String value) {
		this.devType = value;
	}

	/**
	 * Gets the value of the areaNwkId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAreaNwkId() {
		return areaNwkId;
	}

	/**
	 * Sets the value of the areaNwkId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAreaNwkId(String value) {
		this.areaNwkId = value;
	}

	/**
	 * Gets the value of the sleepInterval property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSleepInterval() {
		return sleepInterval;
	}

	/**
	 * Sets the value of the sleepInterval property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSleepInterval(BigInteger value) {
		this.sleepInterval = value;
	}

	/**
	 * Gets the value of the sleepDuration property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSleepDuration() {
		return sleepDuration;
	}

	/**
	 * Sets the value of the sleepDuration property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSleepDuration(BigInteger value) {
		this.sleepDuration = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatus(String value) {
		this.status = value;
	}

	/**
	 * Gets the value of the listOfNeighbors property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the listOfNeighbors property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getListOfNeighbors().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getListOfNeighbors() {
		if (listOfNeighbors == null) {
			listOfNeighbors = new ArrayList<String>();
		}
		return this.listOfNeighbors;
	}

	/**
	 * Gets the value of the childResource property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the childResource property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getChildResource().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ChildResourceRef }
	 * 
	 * 
	 */
	public List<ChildResourceRef> getChildResource() {
		if (childResource == null) {
			childResource = new ArrayList<ChildResourceRef>();
		}
		return this.childResource;
	}

	/**
	 * Gets the value of the subscription property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subscription property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubscription().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Subscription }
	 * 
	 * 
	 */
	public List<Subscription> getSubscription() {
		if (subscription == null) {
			subscription = new ArrayList<Subscription>();
		}
		return this.subscription;
	}

}
