/*******************************************************************************
 * Copyright (c) 2013-2016 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Initial Contributors:
 *     Thierry Monteil : Project manager, technical co-manager
 *     Mahdi Ben Alaya : Technical co-manager
 *     Samir Medjiah : Technical co-manager
 *     Khalil Drira : Strategy expert
 *     Guillaume Garzone : Developer
 *     François Aïssaoui : Developer
 *
 * New contributors :
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 03:56:27 PM CEST 
//

package org.eclipse.om2m.commons.resource;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for execReqArgsListType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="execReqArgsListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="reset" type="{http://www.onem2m.org/xml/protocols}resetArgsType" maxOccurs="unbounded"/>
 *         &lt;element name="reboot" type="{http://www.onem2m.org/xml/protocols}rebootArgsType" maxOccurs="unbounded"/>
 *         &lt;element name="upload" type="{http://www.onem2m.org/xml/protocols}uploadArgsType" maxOccurs="unbounded"/>
 *         &lt;element name="download" type="{http://www.onem2m.org/xml/protocols}downloadArgsType" maxOccurs="unbounded"/>
 *         &lt;element name="softwareInstall" type="{http://www.onem2m.org/xml/protocols}softwareInstallArgsType" maxOccurs="unbounded"/>
 *         &lt;element name="softwareUpdate" type="{http://www.onem2m.org/xml/protocols}softwareUpdateArgsType" maxOccurs="unbounded"/>
 *         &lt;element name="softwareUninstall" type="{http://www.onem2m.org/xml/protocols}softwareUninstallArgsType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "execReqArgsListType", propOrder = { "reset", "reboot",
		"upload", "download", "softwareInstall", "softwareUpdate",
		"softwareUninstall" })
public class ExecReqArgsListType {

	protected List<ResetArgsType> reset;
	protected List<RebootArgsType> reboot;
	protected List<UploadArgsType> upload;
	protected List<DownloadArgsType> download;
	protected List<SoftwareInstallArgsType> softwareInstall;
	protected List<SoftwareUpdateArgsType> softwareUpdate;
	protected List<SoftwareUninstallArgsType> softwareUninstall;

	/**
	 * Gets the value of the reset property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the reset property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getReset().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ResetArgsType }
	 * 
	 * 
	 */
	public List<ResetArgsType> getReset() {
		if (reset == null) {
			reset = new ArrayList<ResetArgsType>();
		}
		return this.reset;
	}

	/**
	 * Gets the value of the reboot property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the reboot property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getReboot().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RebootArgsType }
	 * 
	 * 
	 */
	public List<RebootArgsType> getReboot() {
		if (reboot == null) {
			reboot = new ArrayList<RebootArgsType>();
		}
		return this.reboot;
	}

	/**
	 * Gets the value of the upload property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the upload property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUpload().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link UploadArgsType }
	 * 
	 * 
	 */
	public List<UploadArgsType> getUpload() {
		if (upload == null) {
			upload = new ArrayList<UploadArgsType>();
		}
		return this.upload;
	}

	/**
	 * Gets the value of the download property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the download property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDownload().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DownloadArgsType }
	 * 
	 * 
	 */
	public List<DownloadArgsType> getDownload() {
		if (download == null) {
			download = new ArrayList<DownloadArgsType>();
		}
		return this.download;
	}

	/**
	 * Gets the value of the softwareInstall property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the softwareInstall property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSoftwareInstall().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SoftwareInstallArgsType }
	 * 
	 * 
	 */
	public List<SoftwareInstallArgsType> getSoftwareInstall() {
		if (softwareInstall == null) {
			softwareInstall = new ArrayList<SoftwareInstallArgsType>();
		}
		return this.softwareInstall;
	}

	/**
	 * Gets the value of the softwareUpdate property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the softwareUpdate property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSoftwareUpdate().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SoftwareUpdateArgsType }
	 * 
	 * 
	 */
	public List<SoftwareUpdateArgsType> getSoftwareUpdate() {
		if (softwareUpdate == null) {
			softwareUpdate = new ArrayList<SoftwareUpdateArgsType>();
		}
		return this.softwareUpdate;
	}

	/**
	 * Gets the value of the softwareUninstall property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the softwareUninstall property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSoftwareUninstall().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SoftwareUninstallArgsType }
	 * 
	 * 
	 */
	public List<SoftwareUninstallArgsType> getSoftwareUninstall() {
		if (softwareUninstall == null) {
			softwareUninstall = new ArrayList<SoftwareUninstallArgsType>();
		}
		return this.softwareUninstall;
	}

}
