/*******************************************************************************
 * Copyright (c) 2013-2016 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Initial Contributors:
 *     Thierry Monteil : Project manager, technical co-manager
 *     Mahdi Ben Alaya : Technical co-manager
 *     Samir Medjiah : Technical co-manager
 *     Khalil Drira : Strategy expert
 *     Guillaume Garzone : Developer
 *     François Aïssaoui : Developer
 *
 * New contributors :
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.07.08 at 01:02:29 PM CEST
//

package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java Class for StatusCode.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="StatusCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STATUS_OK"/>
 *     &lt;enumeration value="STATUS_ACCEPTED"/>
 *     &lt;enumeration value="STATUS_BAD_REQUEST"/>
 *     &lt;enumeration value="STATUS_PERMISSION_DENIED"/>
 *     &lt;enumeration value="STATUS_FORBIDDEN"/>
 *     &lt;enumeration value="STATUS_NOT_FOUND"/>
 *     &lt;enumeration value="STATUS_METHOD_NOT_ALLOWED"/>
 *     &lt;enumeration value="STATUS_NOT_ACCEPTABLE"/>
 *     &lt;enumeration value="STATUS_REQUEST_TIMEOUT"/>
 *     &lt;enumeration value="STATUS_CONFLICT"/>
 *     &lt;enumeration value="STATUS_UNSUPPORTED_MEDIA_TYPE"/>
 *     &lt;enumeration value="STATUS_INTERNAL_SERVER_ERROR"/>
 *     &lt;enumeration value="STATUS_NOT_IMPLEMENTED"/>
 *     &lt;enumeration value="STATUS_BAD_GATEWAY"/>
 *     &lt;enumeration value="STATUS_SERVICE_UNAVAILABLE"/>
 *     &lt;enumeration value="STATUS_GATEWAY_TIMEOUT"/>
 *     &lt;enumeration value="STATUS_DELETED"/>
 *     &lt;enumeration value="STATUS_EXPIRED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "StatusCode")
@XmlEnum
public enum StatusCode {

	STATUS_OK, STATUS_ACCEPTED, STATUS_BAD_REQUEST, STATUS_PERMISSION_DENIED, STATUS_FORBIDDEN, STATUS_NOT_FOUND, STATUS_METHOD_NOT_ALLOWED, STATUS_NOT_ACCEPTABLE, STATUS_REQUEST_TIMEOUT, STATUS_CONFLICT, STATUS_UNSUPPORTED_MEDIA_TYPE, STATUS_INTERNAL_SERVER_ERROR, STATUS_NOT_IMPLEMENTED, STATUS_BAD_GATEWAY, STATUS_SERVICE_UNAVAILABLE, STATUS_GATEWAY_TIMEOUT, STATUS_DELETED, STATUS_CREATED, STATUS_AUTHORIZATION_NOT_ADDED, STATUS_EXPIRED, STATUS_ALREADY_EXISTS;

	public String value() {
		return name();
	}

	public static StatusCode fromValue(String v) {
		return valueOf(v);
	}

}
